### ISSUE TITLE
jindofs-sdk.jar在mac环境下会报NPE

### ISSUE THREAD

**Issue by nicppa** [aliyun/alibabacloud-jindofs#69]
Exception in thread "main" java.lang.RuntimeException: JbootNative loading failed: java.lang.NullPointerException
	at com.alibaba.jboot.NativeCodeLoader.extractLibraryFile(NativeCodeLoader.java:252)
	at com.alibaba.jboot.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:86)
	at com.alibaba.jboot.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:59)
	at com.alibaba.jboot.NativeCodeLoader.load(NativeCodeLoader.java:39)
	at com.alibaba.jboot.JbootNative.<clinit>(JbootNative.java:19)
	at com.aliyun.emr.fs.common.AbstractJindoFileSystem.initialize(AbstractJindoFileSystem.java:104)
	at com.aliyun.emr.fs.oss.JindoOssFileSystem.initialize(JindoOssFileSystem.java:97)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3247)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:121)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3296)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3264)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:475)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:438)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:538)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:310)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)

![企业微信截图_7e00113d-4d10-473e-9f51-f0a6ce63be32](https://user-images.githubusercontent.com/7270061/122381330-62d5ee80-cf9b-11eb-8ad3-d334c1735b6a.png)

**Comment by nicppa** [comment]
用错jar包了。
